databases:
  - name: shop-db
    plan: free
    databaseName: shop_db
    user: shop_user

services:
  - type: web
    name: django-shop
    plan: free
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn shop.asgi:application -k uvicorn.workers.UvicornWorker --timeout 120 --log-file -"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
